name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
    
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600         


      - name: print
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo $DATABASE_URL

      - name: Build image 
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: docker build -t registry.digitalocean.com/docker-cours/sniphub-back:main-${{ github.run_number }} . --build-arg DATABASE_URL=$DATABASE_URL
        



      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/docker-cours/sniphub-back:main-${{ github.run_number }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.actor }}/sniphub-deploy
          event-type: new-image-back
          client-payload: '{"image": "registry.digitalocean.com/docker-cours/sniphub-back:main-${{ github.run_number }}"}'
    services:

      db:
        image: mat31/sniphub-kubectl:github-0.1
        env:
          KUBECONFIG: "${{ secrets.KUBE_CONFIG }}"
          NAMESPACE: sniphub
          POD: postgres-statefulset-0
          PORTS: 5432:5432  
        ports:
          - 5432:5432