name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      
      - name: Set up portforwardd
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: port-forward pods/postgres-statefulset-0 5454:5432 -n sniphub 

      - name: Build image 
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: docker build -t registry.digitalocean.com/docker-cours/sniphub-back:main-${{ github.run_number }} .

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/docker-cours/sniphub-back:main-${{ github.run_number }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.actor }}/sniphub-deploy
          event-type: new-image-back
          client-payload: '{"image": "registry.digitalocean.com/docker-cours/sniphub-back:main-${{ github.run_number }}"}'
